=== Albe83/audit-trial/audit-trail-v1.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://guidelines.sisal.cloudnative.apps/audit-trail-v1.schema.json",
    "title": "Audit Trails",
    "description": "An audit trail is a security relevant chronological record that provide documentary evidence of the sequence of activities that have affected a specific system.",
    "type": "object",
    "properties": {
        "time": {
            "type": "object",
            "description": "Temporal informations about when an activity is happen.",
            "properties": {
                "when": {
                    "type": "string",
                    "format": "date-time",
                    "description": "When the activity occurred."
                },
                "duration": {
                    "type": "string",
                    "format": "duration",
                    "description": "(Optional) How long the activity will produce effects."
                }
            },
            "required": ["when"]
        },
        "subject": {
            "type": "object",
            "description": "Functional user who performed the task.",
            "properties": {
                "kind": {
                    "enum": ["user", "machine", "system", "other"],
                    "description": "Type of user. The value \"system\" define an internal action."
                },
                "id": {
                    "type": "string",
                    "description": "Unique identifier of the actor. If \"kind\" value is \"system\" id should be identify which part of system have started activity."
                },
                "agent": {
                    "type": ["string", "object"],
                    "description": "(Optional) Software or tool used by Subject to act."
                }
            },
            "required": ["kind", "id"]
        },
        "action": {
            "type": "object",
            "description": "Describe action done by Subject.",
            "properties": {
                "kind": {
                    "enum": ["dispositive", "informative"],
                    "description": "Action is \"Dispositive\" when change functional state, or \"Informative\" when access to functional state."
                },
                "operation": {
                    "type": "string",
                    "description": ""
                },
                "status": {
                    "type": "object",
                    "description": "",
                    "properties": {
                        "result": {
                            "enum": ["succeeded", "failed"],
                            "description": ""
                        },
                        "code": {
                            "type": "integer",
                            "description": ""
                        },
                        "reason": {
                            "type": "string",
                            "description": "",
                            "maxLength": 25
                        }
                    },
                    "required": ["result"]
                },
                "changes": {
                    "type": "array",
                    "description": "",
                    "items": {
                        "type": "object",
                        "properties": {
                            "param": {
                                "type": "string",
                                "description": ""
                            },
                            "oldValue": {
                                "description": ""
                            },
                            "newValue": {
                                "description": ""
                            }
                        }
                    }
                }
            },
            "required": ["kind", "operation", "status"]
        },
        "target": {
            "type": "object",
            "description": "",
            "properties": {
                "kind": {
                    "type": "string",
                    "pattern": "^urn:[a-z0-9]+[a-z0-9-_:]*[a-z0-9]+[a-z0-9-_]$",
                    "description": "URN-like resource type description."
                },
                "id": {
                    "type": ["string", "integer"],
                    "minimum": 0,
                    "minLength": 1,
                    "description": "Resource identifier."
                }
            },
            "required": ["kind", "id"]
        }
    },
    "required": ["time", "subject", "action"]
}

=== Albe83/audit-trial/examples/logout-succeeded.json
{
    "time": {
        "when": "2023-12-01T01:01:01+01:00"
    },
    "subject": {
        "kind": "user",
        "id": "user_id",
        "agent": {
            "client": "jsClient",
            "version": "v1.0.0"
        }
    },
    "action": {
        "kind": "dispositive",
        "operation": "logout",
        "status": {
            "result": "succeeded",
            "code": 0
        }
    },
    "target": {
        "kind": "urn:ietf:params:oauth:grant-type:jwt-bearer",
        "id": "jws_id_identify_user_session"
    }
}

=== Albe83/audit-trial/examples/personal-info-succeeded.json
{
    "time": {
        "when": "2023-12-01T01:01:01+01:00"
    },
    "subject": {
        "kind": "user",
        "id": "user_id",
        "agent": {
            "client": "jsClient",
            "version": "v1.0.0",
            "session": "jti_or_session_id"
        }
    },
    "action": {
        "kind": "informative",
        "operation": "getPersonalInfo",
        "status": {
            "result": "succeeded",
            "code": 0
        }
    },
    "target": {
        "kind": "urn:my-company-name:pim:user",
        "id": "user_id"
    }
}
